2025-04-23 21:59:21,097 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 21:59:21,097 INFO: Using device: cpu
2025-04-23 21:59:21,101 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:00:23,045 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:00:23,046 INFO: Using device: cpu
2025-04-23 22:00:23,059 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:00:30,431 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:00:30,431 INFO: Using device: cpu
2025-04-23 22:00:30,434 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:08:59,944 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:08:59,945 INFO: Using device: cpu
2025-04-23 22:08:59,948 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:13,440 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:13,440 INFO: Using device: cpu
2025-04-23 22:09:13,444 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:29,337 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:29,337 INFO: Using device: cpu
2025-04-23 22:09:29,341 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:30,875 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:30,875 INFO: Using device: cpu
2025-04-23 22:09:30,879 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:39,817 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:39,817 INFO: Using device: cpu
2025-04-23 22:09:39,820 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:54,396 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:54,397 INFO: Using device: cpu
2025-04-23 22:09:54,400 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:09:55,879 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:09:55,879 INFO: Using device: cpu
2025-04-23 22:09:55,883 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:21,018 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:21,019 INFO: Using device: cpu
2025-04-23 22:10:21,023 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:27,959 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:27,960 INFO: Using device: cpu
2025-04-23 22:10:27,964 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:30,600 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:30,600 INFO: Using device: cpu
2025-04-23 22:10:30,603 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:34,808 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:34,808 INFO: Using device: cpu
2025-04-23 22:10:34,811 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:47,301 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:47,301 INFO: Using device: cpu
2025-04-23 22:10:47,305 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:49,205 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:49,205 INFO: Using device: cpu
2025-04-23 22:10:49,209 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:10:55,298 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:10:55,299 INFO: Using device: cpu
2025-04-23 22:10:55,302 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:05,284 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:05,285 INFO: Using device: cpu
2025-04-23 22:11:05,289 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:08,436 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:08,436 INFO: Using device: cpu
2025-04-23 22:11:08,441 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:14,561 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:14,562 INFO: Using device: cpu
2025-04-23 22:11:14,566 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:16,803 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:16,803 INFO: Using device: cpu
2025-04-23 22:11:16,807 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:29,030 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:29,031 INFO: Using device: cpu
2025-04-23 22:11:29,034 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:30,729 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:30,729 INFO: Using device: cpu
2025-04-23 22:11:30,733 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:35,931 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:35,932 INFO: Using device: cpu
2025-04-23 22:11:35,935 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:44,921 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:44,923 INFO: Using device: cpu
2025-04-23 22:11:44,926 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:56,284 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:56,284 INFO: Using device: cpu
2025-04-23 22:11:56,288 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:11:57,786 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:11:57,786 INFO: Using device: cpu
2025-04-23 22:11:57,789 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:01,208 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:01,208 INFO: Using device: cpu
2025-04-23 22:12:01,212 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:07,704 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:07,704 INFO: Using device: cpu
2025-04-23 22:12:07,708 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:09,096 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:09,097 INFO: Using device: cpu
2025-04-23 22:12:09,100 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:16,057 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:16,057 INFO: Using device: cpu
2025-04-23 22:12:16,061 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:22,751 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:22,752 INFO: Using device: cpu
2025-04-23 22:12:22,756 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:25,540 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:25,541 INFO: Using device: cpu
2025-04-23 22:12:25,544 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:30,759 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:30,760 INFO: Using device: cpu
2025-04-23 22:12:30,763 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:32,501 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:32,501 INFO: Using device: cpu
2025-04-23 22:12:32,505 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:38,247 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:38,248 INFO: Using device: cpu
2025-04-23 22:12:38,251 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:42,958 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:42,958 INFO: Using device: cpu
2025-04-23 22:12:42,962 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:46,396 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:46,397 INFO: Using device: cpu
2025-04-23 22:12:46,401 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:12:52,354 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:12:52,355 INFO: Using device: cpu
2025-04-23 22:12:52,358 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:13:59,904 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:13:59,905 INFO: Using device: cpu
2025-04-23 22:13:59,908 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:11,368 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:11,368 INFO: Using device: cpu
2025-04-23 22:14:11,372 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:12,980 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:12,980 INFO: Using device: cpu
2025-04-23 22:14:12,983 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:23,741 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:23,741 INFO: Using device: cpu
2025-04-23 22:14:23,745 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:26,470 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:26,470 INFO: Using device: cpu
2025-04-23 22:14:26,473 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:31,802 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:31,802 INFO: Using device: cpu
2025-04-23 22:14:31,806 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:36,707 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:36,707 INFO: Using device: cpu
2025-04-23 22:14:36,711 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:14:41,909 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:14:41,909 INFO: Using device: cpu
2025-04-23 22:14:41,913 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:18:49,145 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:18:49,147 INFO: Using device: cpu
2025-04-23 22:18:49,150 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:03,405 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:03,406 INFO: Using device: cpu
2025-04-23 22:19:03,409 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:05,889 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:05,889 INFO: Using device: cpu
2025-04-23 22:19:05,892 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:19:50,805 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:19:50,805 INFO: Using device: cpu
2025-04-23 22:19:50,808 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:20:53,731 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:20:53,731 INFO: Using device: cpu
2025-04-23 22:20:53,735 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:21:53,405 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:21:53,406 INFO: Using device: cpu
2025-04-23 22:21:53,409 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:22:07,587 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:22:07,588 INFO: Using device: cpu
2025-04-23 22:22:07,591 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:23:24,724 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:23:24,725 INFO: Using device: cpu
2025-04-23 22:23:24,728 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:25:56,694 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:25:56,694 INFO: Using device: cpu
2025-04-23 22:25:56,698 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:26:16,377 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:26:16,377 INFO: Using device: cpu
2025-04-23 22:26:16,381 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-23 22:26:17,898 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-23 22:26:17,898 INFO: Using device: cpu
2025-04-23 22:26:17,902 ERROR: Failed to load model checkpoint
Traceback (most recent call last):
  File "/Users/derekjrussell/Documents/repos/ConnectFourGame/ml_service/ml_service.py", line 56, in <module>
    checkpoint = torch.load(paths["ckpt"], map_location=device)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/derekjrussell/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt'
2025-04-24 01:57:54,256 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 01:57:54,256 INFO: Using device: cpu
2025-04-24 01:57:54,278 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 02:14:31,105 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:14:31,138 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:14:31,138 INFO: Response status: 200
2025-04-24 02:14:55,842 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:14:55,848 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:14:55,848 INFO: Response status: 200
2025-04-24 02:18:35,647 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:18:35,663 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:18:35,664 INFO: Response status: 200
2025-04-24 02:22:24,402 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:22:24,412 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:22:24,413 INFO: Response status: 200
2025-04-24 02:24:07,145 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 02:24:07,145 INFO: Using device: cpu
2025-04-24 02:24:07,165 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 02:31:48,624 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 02:31:48,625 INFO: Using device: cpu
2025-04-24 02:31:48,645 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 02:31:54,889 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 02:31:54,889 INFO: Using device: cpu
2025-04-24 02:31:54,896 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 02:33:13,675 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:33:13,718 INFO: Predicted move: 3 with probs: [0.0034953923895955086, 0.026883170008659363, 0.17079992592334747, 0.46243542432785034, 0.27917516231536865, 0.04538682848215103, 0.011824238114058971]
2025-04-24 02:33:13,718 INFO: Response status: 200
2025-04-24 02:38:42,308 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:38:42,320 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:38:42,321 INFO: Response status: 200
2025-04-24 02:41:01,637 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:41:01,644 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:41:01,645 INFO: Response status: 200
2025-04-24 02:41:03,779 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:41:03,785 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 02:41:03,786 INFO: Response status: 200
2025-04-24 02:41:05,840 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:41:05,846 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 02:41:05,847 INFO: Response status: 200
2025-04-24 02:41:55,399 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:41:55,411 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 02:41:55,412 INFO: Response status: 200
2025-04-24 02:41:57,147 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:41:57,155 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 02:41:57,156 INFO: Response status: 200
2025-04-24 02:42:00,689 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 02:42:00,693 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 02:42:00,693 INFO: Response status: 200
2025-04-24 12:42:04,661 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 12:42:04,661 INFO: Using device: cpu
2025-04-24 12:42:04,670 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 12:43:47,695 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:43:47,703 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 12:43:47,704 INFO: Response status: 200
2025-04-24 12:43:49,359 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:43:49,365 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 12:43:49,366 INFO: Response status: 200
2025-04-24 12:43:51,791 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:43:51,796 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 12:43:51,797 INFO: Response status: 200
2025-04-24 12:43:54,772 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:43:54,777 INFO: Predicted move: 1 with probs: [0.27615678310394287, 0.6599847674369812, 0.02767724171280861, 0.008633783087134361, 0.008057000115513802, 0.013019951991736889, 0.006470475811511278]
2025-04-24 12:43:54,778 INFO: Response status: 200
2025-04-24 12:43:57,854 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:43:57,861 INFO: Predicted move: 1 with probs: [0.3273959159851074, 0.6169535517692566, 0.027056124061346054, 0.008771253749728203, 0.0052744620479643345, 0.00962753314524889, 0.004921210464090109]
2025-04-24 12:43:57,862 INFO: Response status: 200
2025-04-24 12:44:02,946 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 12:44:02,954 INFO: Predicted move: 0 with probs: [0.3997054994106293, 0.39817914366722107, 0.06461489945650101, 0.06185976415872574, 0.03851498290896416, 0.022134628146886826, 0.014991195872426033]
2025-04-24 12:44:02,954 INFO: Response status: 200
2025-04-24 12:59:56,551 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 12:59:56,551 INFO: Using device: cpu
2025-04-24 12:59:56,576 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 13:00:19,021 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:19,047 INFO: Predicted move: 2 with probs: [0.00795811042189598, 0.04558105394244194, 0.4200504422187805, 0.3984396457672119, 0.070785753428936, 0.04825539141893387, 0.00892962608486414]
2025-04-24 13:00:19,048 INFO: Response status: 200
2025-04-24 13:00:32,975 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:32,979 INFO: Predicted move: 1 with probs: [0.14299863576889038, 0.43586915731430054, 0.21658410131931305, 0.043422844260931015, 0.019595667719841003, 0.11084353923797607, 0.03068615309894085]
2025-04-24 13:00:32,979 INFO: Response status: 200
2025-04-24 13:00:36,655 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:36,657 INFO: Predicted move: 2 with probs: [0.09111033380031586, 0.17225968837738037, 0.4176463484764099, 0.07381514459848404, 0.019729025661945343, 0.17663957178592682, 0.048799917101860046]
2025-04-24 13:00:36,658 INFO: Response status: 200
2025-04-24 13:00:38,804 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:38,807 INFO: Predicted move: 1 with probs: [0.17536835372447968, 0.26756346225738525, 0.1982542723417282, 0.010189007967710495, 0.012453495524823666, 0.2164512723684311, 0.11972015351057053]
2025-04-24 13:00:38,807 INFO: Response status: 200
2025-04-24 13:00:40,871 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:40,877 INFO: Predicted move: 0 with probs: [0.43390369415283203, 0.30866605043411255, 0.05313313752412796, 0.01233668439090252, 0.009822707623243332, 0.09389740228652954, 0.08824022859334946]
2025-04-24 13:00:40,878 INFO: Response status: 200
2025-04-24 13:00:42,936 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:42,939 INFO: Predicted move: 0 with probs: [0.3570602238178253, 0.17441508173942566, 0.09374716877937317, 0.017208311706781387, 0.011610164307057858, 0.1839171051979065, 0.16204193234443665]
2025-04-24 13:00:42,939 INFO: Response status: 200
2025-04-24 13:00:47,437 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:47,440 INFO: Predicted move: 5 with probs: [0.2791757881641388, 0.11885245144367218, 0.11718063801527023, 0.03496317192912102, 0.005960205569863319, 0.33110201358795166, 0.11276572197675705]
2025-04-24 13:00:47,441 INFO: Response status: 200
2025-04-24 13:00:50,872 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:50,875 INFO: Predicted move: 3 with probs: [0.21373631060123444, 0.07487642019987106, 0.15864697098731995, 0.31237927079200745, 0.008395311422646046, 0.18435883522033691, 0.04760686680674553]
2025-04-24 13:00:50,876 INFO: Response status: 200
2025-04-24 13:00:53,986 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:53,989 INFO: Predicted move: 0 with probs: [0.332522988319397, 0.1076393574476242, 0.11868662387132645, 0.19440627098083496, 0.006786753889173269, 0.19049930572509766, 0.04945874959230423]
2025-04-24 13:00:53,989 INFO: Response status: 200
2025-04-24 13:00:57,338 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:57,341 INFO: Predicted move: 0 with probs: [0.31908848881721497, 0.11119003593921661, 0.11240764707326889, 0.20539231598377228, 0.008334172889590263, 0.1887861043214798, 0.05480122193694115]
2025-04-24 13:00:57,342 INFO: Response status: 200
2025-04-24 13:00:59,486 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:00:59,489 INFO: Predicted move: 5 with probs: [0.1628200113773346, 0.06525065749883652, 0.14055117964744568, 0.19114744663238525, 0.008502081036567688, 0.35447415709495544, 0.07725455611944199]
2025-04-24 13:00:59,490 INFO: Response status: 200
2025-04-24 13:01:00,871 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:01:00,873 INFO: Predicted move: 3 with probs: [0.16850653290748596, 0.06458364427089691, 0.1364479959011078, 0.28091752529144287, 0.011103241704404354, 0.26460638642311096, 0.07383465766906738]
2025-04-24 13:01:00,874 INFO: Response status: 200
2025-04-24 13:02:27,234 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:02:27,251 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:02:27,252 INFO: Response status: 200
2025-04-24 13:04:18,172 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 13:04:18,172 INFO: Using device: cpu
2025-04-24 13:04:18,193 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 13:04:29,696 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:29,727 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:04:29,728 INFO: Response status: 200
2025-04-24 13:04:31,213 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:31,216 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 13:04:31,216 INFO: Response status: 200
2025-04-24 13:04:35,374 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:35,377 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 13:04:35,377 INFO: Response status: 200
2025-04-24 13:04:36,824 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:36,827 INFO: Predicted move: 1 with probs: [0.16286137700080872, 0.31873905658721924, 0.14653141796588898, 0.17056512832641602, 0.14224614202976227, 0.04331142082810402, 0.01574547588825226]
2025-04-24 13:04:36,827 INFO: Response status: 200
2025-04-24 13:04:37,674 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:37,677 INFO: Predicted move: 1 with probs: [0.2725526690483093, 0.32820969820022583, 0.09849503636360168, 0.037648484110832214, 0.09591420739889145, 0.0745653584599495, 0.09261443465948105]
2025-04-24 13:04:37,677 INFO: Response status: 200
2025-04-24 13:04:41,223 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:41,226 INFO: Predicted move: 4 with probs: [0.15148049592971802, 0.13671113550662994, 0.11781791597604752, 0.10621286183595657, 0.2294430136680603, 0.1287972778081894, 0.12953738868236542]
2025-04-24 13:04:41,226 INFO: Response status: 200
2025-04-24 13:04:47,376 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:04:47,379 INFO: Predicted move: 0 with probs: [0.22185039520263672, 0.1247219666838646, 0.1726868748664856, 0.08667320758104324, 0.03821206092834473, 0.1512744128704071, 0.2045810967683792]
2025-04-24 13:04:47,379 INFO: Response status: 200
2025-04-24 13:19:40,739 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 13:19:40,740 INFO: Using device: cpu
2025-04-24 13:19:40,764 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 13:19:51,754 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:19:51,795 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:19:51,795 INFO: Response status: 200
2025-04-24 13:20:00,673 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:00,676 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 13:20:00,676 INFO: Response status: 200
2025-04-24 13:20:03,333 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:03,335 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 13:20:03,336 INFO: Response status: 200
2025-04-24 13:20:16,846 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:16,850 INFO: Predicted move: 4 with probs: [0.005525162909179926, 0.03164956346154213, 0.09492707252502441, 0.31897103786468506, 0.48278340697288513, 0.05159251391887665, 0.014551196247339249]
2025-04-24 13:20:16,851 INFO: Response status: 200
2025-04-24 13:20:18,313 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:18,316 INFO: Predicted move: 2 with probs: [0.05899456888437271, 0.17258904874324799, 0.274246484041214, 0.1322510987520218, 0.07973270118236542, 0.19650499522686005, 0.08568112552165985]
2025-04-24 13:20:18,317 INFO: Response status: 200
2025-04-24 13:20:19,945 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:19,948 INFO: Predicted move: 3 with probs: [0.003962986171245575, 0.018623098731040955, 0.1529422402381897, 0.6086946725845337, 0.18245179951190948, 0.02895086258649826, 0.004374304320663214]
2025-04-24 13:20:19,949 INFO: Response status: 200
2025-04-24 13:20:22,298 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:22,300 INFO: Predicted move: 2 with probs: [0.08241162449121475, 0.28125694394111633, 0.3920923173427582, 0.14091259241104126, 0.046576812863349915, 0.04770275950431824, 0.009046928025782108]
2025-04-24 13:20:22,301 INFO: Response status: 200
2025-04-24 13:20:26,179 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:26,182 INFO: Predicted move: 2 with probs: [0.034877676516771317, 0.0714036300778389, 0.3894045054912567, 0.2792069911956787, 0.074541375041008, 0.12748226523399353, 0.02308349683880806]
2025-04-24 13:20:26,182 INFO: Response status: 200
2025-04-24 13:20:35,613 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:35,617 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:20:35,618 INFO: Response status: 200
2025-04-24 13:20:36,465 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:36,468 INFO: Predicted move: 1 with probs: [0.2209879457950592, 0.2653885781764984, 0.1793496310710907, 0.1430283933877945, 0.05006053298711777, 0.09024088829755783, 0.050944048911333084]
2025-04-24 13:20:36,468 INFO: Response status: 200
2025-04-24 13:20:38,879 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:38,882 INFO: Predicted move: 1 with probs: [0.2844313085079193, 0.28506946563720703, 0.17234542965888977, 0.0573635958135128, 0.02108815126121044, 0.09096008539199829, 0.08874189853668213]
2025-04-24 13:20:38,882 INFO: Response status: 200
2025-04-24 13:20:39,812 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:39,814 INFO: Predicted move: 0 with probs: [0.28026628494262695, 0.20659750699996948, 0.13758762180805206, 0.12806987762451172, 0.043660834431648254, 0.10463189333677292, 0.09918588399887085]
2025-04-24 13:20:39,815 INFO: Response status: 200
2025-04-24 13:20:42,445 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:20:42,448 INFO: Predicted move: 0 with probs: [0.2906615436077118, 0.18743979930877686, 0.14490367472171783, 0.12621797621250153, 0.02718316949903965, 0.12390650063753128, 0.09968725591897964]
2025-04-24 13:20:42,448 INFO: Response status: 200
2025-04-24 13:26:44,774 INFO: Model paths: {'model_dir': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models', 'ckpt': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt', 'ts_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net_ts.pt', 'onnx_model': '/Users/derekjrussell/Documents/repos/ConnectFourGame/models/policy_net.onnx'}
2025-04-24 13:26:44,774 INFO: Using device: cpu
2025-04-24 13:26:44,796 INFO: Loaded model checkpoint from /Users/derekjrussell/Documents/repos/ConnectFourGame/models/best_policy_net.pt
2025-04-24 13:26:53,959 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:26:53,986 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:26:53,987 INFO: Response status: 200
2025-04-24 13:26:55,314 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:26:55,317 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 13:26:55,317 INFO: Response status: 200
2025-04-24 13:26:57,697 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:26:57,700 INFO: Predicted move: 2 with probs: [0.11680376529693604, 0.19746153056621552, 0.24911965429782867, 0.06541852653026581, 0.03841695189476013, 0.20629262924194336, 0.12648695707321167]
2025-04-24 13:26:57,700 INFO: Response status: 200
2025-04-24 13:26:59,997 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:00,000 INFO: Predicted move: 1 with probs: [0.16286137700080872, 0.31873905658721924, 0.14653141796588898, 0.17056512832641602, 0.14224614202976227, 0.04331142082810402, 0.01574547588825226]
2025-04-24 13:27:00,000 INFO: Response status: 200
2025-04-24 13:27:02,247 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:02,250 INFO: Predicted move: 1 with probs: [0.19418805837631226, 0.25245440006256104, 0.2478116750717163, 0.1772732436656952, 0.07145069539546967, 0.0393296517431736, 0.01749230921268463]
2025-04-24 13:27:02,250 INFO: Response status: 200
2025-04-24 13:27:04,798 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:04,800 INFO: Predicted move: 0 with probs: [0.37547099590301514, 0.2533155083656311, 0.10616181790828705, 0.07506990432739258, 0.05864100903272629, 0.04996774345636368, 0.08137296140193939]
2025-04-24 13:27:04,801 INFO: Response status: 200
2025-04-24 13:27:22,919 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:22,926 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:27:22,927 INFO: Response status: 200
2025-04-24 13:27:28,599 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:28,602 INFO: Predicted move: 2 with probs: [0.0759061649441719, 0.20997342467308044, 0.34362107515335083, 0.07893379032611847, 0.03572327271103859, 0.19581900537014008, 0.06002329662442207]
2025-04-24 13:27:28,603 INFO: Response status: 200
2025-04-24 13:27:30,286 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:30,294 INFO: Predicted move: 2 with probs: [0.10981888324022293, 0.18110117316246033, 0.2273169904947281, 0.08782690763473511, 0.04733959957957268, 0.21413454413414001, 0.13246195018291473]
2025-04-24 13:27:30,294 INFO: Response status: 200
2025-04-24 13:27:31,198 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:31,201 INFO: Predicted move: 1 with probs: [0.21448412537574768, 0.49468371272087097, 0.13931085169315338, 0.04481320083141327, 0.020299725234508514, 0.0627867728471756, 0.02362164855003357]
2025-04-24 13:27:31,202 INFO: Response status: 200
2025-04-24 13:27:32,729 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:32,732 INFO: Predicted move: 1 with probs: [0.2471397966146469, 0.35457080602645874, 0.14136463403701782, 0.03906651958823204, 0.02360488288104534, 0.10784202814102173, 0.08641129732131958]
2025-04-24 13:27:32,732 INFO: Response status: 200
2025-04-24 13:27:36,347 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:36,349 INFO: Predicted move: 0 with probs: [0.22288405895233154, 0.20202501118183136, 0.11643415689468384, 0.18098966777324677, 0.07155370712280273, 0.12516577541828156, 0.08094760030508041]
2025-04-24 13:27:36,350 INFO: Response status: 200
2025-04-24 13:27:41,599 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:41,602 INFO: Predicted move: 3 with probs: [0.07032333314418793, 0.0637333020567894, 0.21089081466197968, 0.31487229466438293, 0.06595347076654434, 0.17129218578338623, 0.10293467342853546]
2025-04-24 13:27:41,602 INFO: Response status: 200
2025-04-24 13:27:45,281 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:45,283 INFO: Predicted move: 0 with probs: [0.42670729756355286, 0.23416979610919952, 0.14756172895431519, 0.06569342315196991, 0.01579463854432106, 0.05187171697616577, 0.05820146203041077]
2025-04-24 13:27:45,284 INFO: Response status: 200
2025-04-24 13:27:50,930 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:27:50,933 INFO: Predicted move: 0 with probs: [0.4192010462284088, 0.22599434852600098, 0.10694948583841324, 0.09606365859508514, 0.025179240852594376, 0.061282966285943985, 0.06532929092645645]
2025-04-24 13:27:50,933 INFO: Response status: 200
2025-04-24 13:28:08,337 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:28:08,341 INFO: Predicted move: 3 with probs: [0.006260535214096308, 0.03023683652281761, 0.19628797471523285, 0.44530805945396423, 0.2561464309692383, 0.05122704431414604, 0.014533162117004395]
2025-04-24 13:28:08,341 INFO: Response status: 200
2025-04-24 13:28:09,914 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:28:09,916 INFO: Predicted move: 1 with probs: [0.10991008579730988, 0.35137486457824707, 0.21664807200431824, 0.08305568993091583, 0.05976949259638786, 0.12333100289106369, 0.05591082200407982]
2025-04-24 13:28:09,917 INFO: Response status: 200
2025-04-24 13:28:11,813 INFO: Incoming request: POST http://localhost:8000/predict
2025-04-24 13:28:11,816 INFO: Predicted move: 1 with probs: [0.15896323323249817, 0.3478465676307678, 0.2111758142709732, 0.07235590368509293, 0.03744252771139145, 0.11668790876865387, 0.055527977645397186]
2025-04-24 13:28:11,816 INFO: Response status: 200
